config/routes.rb
Rails.application.routes.draw do

  resources :main_sectors
  resources :absentees
  resources :pledges
  resources :contribution_transactions
  devise_for :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'members#new'
  get  '/members/pledge_amount_query',  to: 'members#query_for_pledge_amount', as: :pledge_amount_query
  get  '/members/pledge_amount_percentage_query',  to: 'members#query_for_pledge_percentage', as: :pledge_amount_percentage_query
  get  '/members/pledge_building_fund_pledge_query',  to: 'members#query_for_pledge_building_fund', as: :pledge_building_fund_pledge_query
  get  '/members/pledge_special_contribution_pledge_query',  to: 'members#query_for_pledge_special_contribution', as: :pledge_special_contribution_pledge_query
  get  '/members/pledge_last_pledge_query',  to: 'members#query_for_last_pledge', as: :pledge_last_pledge_query
  get  '/members/contribution_transactions',  to: 'members#query_for_contribution_transactions', as: :contribution_transactions_query
  get  '/members/member_groups',  to: 'members#query_for_member_groups', as: :member_groups_query
  get  '/members/indexall', to: 'members#indexall'
  get  '/contribution_transactions_member', to: 'contribution_transactions#member'
  get  '/my_contribution_transactions_member', to: 'contribution_transactions#member_records'
  get  '/contribution_transactions_summary', to: 'contribution_transactions#summary'
  get  '/contribution_transactions_summary2', to: 'contribution_transactions#summary2'
  get  '/contribution_transactions_summary3', to: 'contribution_transactions#summary3'
  get  '/contribution_transactions_summary4', to: 'contribution_transactions#summary4'
  get  '/contribution_transactions_bank_summary', to: 'contribution_transactions#bank_summary'
  get  '/contribution_transactions_tpri', to: 'contribution_transactions#tpri'
  get  '/pledges_member', to: 'pledges#member'
  get  '/absent_report', to: 'absentees#absent_report'

  resources :members do
    get :member_group
    get :create_member_group
    get :add_member_group
    get :delete_member_group
    collection do
      post :import
    end
  end
  resources :staffs
  resources :sectors
  resources :sector_transactions

  devise_scope :user do
     get 'logout', :to => 'devise/sessions#destroy'
  end
end

app/models/sector.rb
class Sector < ApplicationRecord
  belongs_to :staff, optional: true
  belongs_to :user, optional: true
  belongs_to :main_sector
  has_many :members
  has_many :contribution_transactions, through: :members
  has_and_belongs_to_many :users

  def self.options_for_select
    order('LOWER(sector_type)').map { |e| [e.sector_type, e.id] }
  end

  def self.options_for_select_type
    order('LOWER(sector_type)').where(new: false, active: true).map { |e| [e.sector_type, e.sector_type] }
  end

  def self.nonactive
    order('LOWER(sector_type)').where(new: false).map { |e| [e.sector_type, e.sector_type] }
  end

  def self.search(search)
    where("sector_type LIKE ?", "%#{search}%")
  end
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :set_sector, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /sectors
  # GET /sectors.json
  def index
    @sectors = Sector.all.order(:staff_id, :sector_type)
    @members = Member.all.order(:staff_id, :sector_type)
  end

  # GET /sectors/1
  # GET /sectors/1.json
  def show
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors
  # POST /sectors.json
  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to @sector, notice: 'Sector was successfully created.' }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1
  # PATCH/PUT /sectors/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to @sector, notice: 'Sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.json
  def destroy
    @sector.destroy
    respond_to do |format|
      format.html { redirect_to sectors_url, notice: 'Sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sector_params
      params.require(:sector).permit(:sector_type, :staff_id, :user_id, :active, :payable, :main_sector_id)
    end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/sectors/_form.html.erb
<%= form_for(sector) do |f| %>
  <% if sector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sector.errors.count, "error") %> prohibited this sector from being saved:</h2>

      <ul>
      <% sector.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= f.label :sector_type %>
        <%= f.text_field :sector_type %>
        <%= f.label :payable %>
        <%= f.check_box :payable %>
        <%= f.label :active %>
        <%= f.check_box :active %>
        <%= f.label :staff_in_charge %>
        <%= f.collection_select :user_ids, User.all, :id, :email, prompt: true %>
        <%= f.label :main_sector %>
        <%= f.collection_select :main_sector_id, MainSector.all, :id, :sector_name, prompt: true %>
    </div>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sectors/edit.html.erb
<% provide(:title, "Sector Edit") %>
<h1>Editing Sector</h1>

<%= render 'form', sector: @sector %>

<%= link_to 'Show', @sector %> |
<%= link_to 'Back', sectors_path %>

app/views/sectors/index.html.erb
<% provide(:title, "Sector Index") %>
<p id="notice"><%= notice %></p>

<h1>Sectors</h1>

<table class="col-md-12 table-bordered table-striped table-condensed cf">
  <thead class="cf">
    <tr>
      <th>ID</th>
      <th>Sector Type</th>
      <th>Men</th>
      <th>Women</th>
      <th>Staff In Charge</th>
      <!-- <th>Action</th> -->
    </tr>
  </thead>

  <tbody>
    <% @sectors.where(active: true).each do |sector| %>
      <tr>
        <td><%= link_to sector.id,edit_sector_path(sector.id) %></td>
        <td><%= sector.sector_type %></td>
        <td><%= sector.members.where(gender: true).count %></td>
        <td><%= sector.members.where(gender: false).count %></td>
        <td>
          <% sector.users.each do |user| %>
            <%= user.email %>,
          <% end %>
        </td>
         <!-- <td><% link_to 'Show', sector %>&nbsp;&nbsp;&nbsp;
            <% link_to 'Edit', edit_sector_path(sector) %>&nbsp;&nbsp;&nbsp;
            <% link_to 'Delete', sector, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %></td> -->

      </tr>
      <% end %>
      <tr>
        <td></td>
        <td style="text-align: right;"><b>Total<b></td>
        <td><%= Member.where(gender: true, sector: Sector.where(active: true).pluck(:id)).count %></td>
        <td><%= Member.where(gender: false, sector: Sector.where(active: true).pluck(:id)).count %></td>
        <td></td>
      </tr>
      <tr>
        <td></td>
        <td style="text-align: right;"><b>Grand Total<b></td>
        <td colspan = 2><center><b><%= @members.where(sector: Sector.where(active: true).pluck(:id)).count %><b><center></td>
        <td></td>
      </tr>
      <tr>
        <td colspan=6></td>
      </tr>
      <tr>
        <td>8</td> <!-- This is supposed to be sector_id for fall away -->
        <td>Cancelled</td>
        <td><%= Member.where(sector_id: 8, gender: true).count %></td>
        <td><%= Member.where(sector_id: 8, gender: false).count %></td>
        <td></td>
      </tr>
      <tr>
        <td>9</td> <!-- This is supposed to be sector_id for passed away -->
        <td>Passed Away</td>
        <td><%= Member.where(sector_id: 9, gender: true).count %></td>
        <td><%= Member.where(sector_id: 9, gender: false).count %></td>
        <td></td>
      </tr>
      <tr>
        <td>10</td> <!-- This is supposed to be sector_id for Move Out -->
        <td>Move Out</td>
        <td><%= Member.where(sector_id: 10, gender: true).count %></td>
        <td><%= Member.where(sector_id: 10, gender: false).count %></td>
        <td></td>
      </tr>
      <tr>
        <td colspan=5></td>
      </tr>
      <tr>
        <td>11</td> <!-- This is supposed to be sector_id for Move In -->
        <td>Move In</td>
        <td><%= Member.where(sector_id: 11, gender: true).count %></td>
        <td><%= Member.where(sector_id: 11, gender: false).count %></td>
        <td>*Must be 0</td>
      </tr>
      <tr>
        <td>12</td> <!-- This is supposed to be sector_id for Restoration -->
        <td>Restoration</td>
        <td><%= Member.where(sector_id: 12, gender: true).count %></td>
        <td><%= Member.where(sector_id: 12, gender: false).count %></td>
        <td>*Must be 0</td>
      </tr>
      <tr>
        <td>13</td> <!-- This is supposed to be sector_id for Baptism -->
        <td>Baptisms</td>
        <td><%= Member.where(sector_id: 13, gender: true).count %></td>
        <td><%= Member.where(sector_id: 13, gender: false).count %></td>
        <td>*Must be 0</td>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Sector', new_sector_path, class: "btn btn btn-primary" , style: 'margin-top: 10px;' %>

<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-90556377-1', 'auto');
ga('send', 'pageview');
</script>

app/views/sectors/new.html.erb
<% provide(:title, "New Sector") %>
<h1>New Sector</h1>

<%= render 'form', sector: @sector %>

<%= link_to 'Back', sectors_path %>

app/views/sectors/show.html.erb
<% provide(:title, "Sector Details") %>
<p id="notice"><%= notice %></p>

<table class="col-md-12 table-bordered table-striped table-condensed cf">
  <thead class="cf">
    <tr>
      <th>Sector Type</th>
      <th>Staff In Charge</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @sector.sector_type %></td>
        <td><%= @sector.user ? @sector.user.email : '' %></td>
      </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_sector_path(@sector) %> |
<%= link_to 'Back', sectors_path %>

<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-90556377-1', 'auto');
ga('send', 'pageview');
</script>