config/routes.rb
Rails.application.routes.draw do

  resources :main_sectors
  resources :absentees
  resources :pledges
  resources :contribution_transactions
  devise_for :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'members#new'
  get  '/members/pledge_amount_query',  to: 'members#query_for_pledge_amount', as: :pledge_amount_query
  get  '/members/pledge_amount_percentage_query',  to: 'members#query_for_pledge_percentage', as: :pledge_amount_percentage_query
  get  '/members/pledge_building_fund_pledge_query',  to: 'members#query_for_pledge_building_fund', as: :pledge_building_fund_pledge_query
  get  '/members/pledge_special_contribution_pledge_query',  to: 'members#query_for_pledge_special_contribution', as: :pledge_special_contribution_pledge_query
  get  '/members/pledge_last_pledge_query',  to: 'members#query_for_last_pledge', as: :pledge_last_pledge_query
  get  '/members/contribution_transactions',  to: 'members#query_for_contribution_transactions', as: :contribution_transactions_query
  get  '/members/member_groups',  to: 'members#query_for_member_groups', as: :member_groups_query
  get  '/members/indexall', to: 'members#indexall'
  get  '/contribution_transactions_member', to: 'contribution_transactions#member'
  get  '/my_contribution_transactions_member', to: 'contribution_transactions#member_records'
  get  '/contribution_transactions_summary', to: 'contribution_transactions#summary'
  get  '/contribution_transactions_summary2', to: 'contribution_transactions#summary2'
  get  '/contribution_transactions_summary3', to: 'contribution_transactions#summary3'
  get  '/contribution_transactions_summary4', to: 'contribution_transactions#summary4'
  get  '/contribution_transactions_bank_summary', to: 'contribution_transactions#bank_summary'
  get  '/contribution_transactions_tpri', to: 'contribution_transactions#tpri'
  get  '/pledges_member', to: 'pledges#member'
  get  '/absent_report', to: 'absentees#absent_report'

  resources :members do
    get :member_group
    get :create_member_group
    get :add_member_group
    get :delete_member_group
    collection do
      post :import
    end
  end
  resources :staffs
  resources :sectors
  resources :sector_transactions

  devise_scope :user do
     get 'logout', :to => 'devise/sessions#destroy'
  end
end

app/controllers/contribution_transactions_controller.rb
class ContributionTransactionsController < ApplicationController
  include ApplicationHelper
  before_action :set_contribution_transaction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:member_records, :summary, :summary2, :summary3]
  before_action :authenticate_user!, only: [:member_records, :summary]

  # GET /contribution_transactions
  # GET /contribution_transactions.json
  def index
    @contribution_transaction = ContributionTransaction.all.order(bank_statement_date: :desc)
    @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).where(member: Member.search(params[:name])) if params[:name] && !params[:name].empty?
    @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).where(paid_by: Member.search(params[:paid_by])) if params[:paid_by] && !params[:paid_by].empty?

    if params[:fund_type] && !params[:fund_type].empty? && params[:fund_type] == "special_contribution"
      @contribution_transaction = @contribution_transaction.query_by_month(params[:year]) if params[:year] && !params[:year].empty?
      @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).query_by_year(params[:year]) if params[:year] && !params[:year].empty?
    else
      @contribution_transaction = @contribution_transaction.query_by_year(params[:month]) if params[:month] && !params[:month].empty?
      @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).query_by_month(params[:month]) if params[:month] && !params[:month].empty?
    end

    if params[:fund_type] && !params[:fund_type].empty? && params[:fund_type] == "special_contribution"
      @contribution_transaction = @contribution_transaction.query_by_month2(params[:bank_statement]) if params[:bank_statement] && !params[:bank_statement].empty?
      @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).query_by_year2(params[:bank_statement]) if params[:bank_statement] && !params[:bank_statement].empty?
    else
      @contribution_transaction = @contribution_transaction.query_by_year2(params[:bank_statement]) if params[:bank_statement] && !params[:bank_statement].empty?
      @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).query_by_month2(params[:bank_statement]) if params[:bank_statement] && !params[:bank_statement].empty?
    end


    @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).query_by_sector(params[:sector]) if params[:sector] && !params[:sector].empty?
    @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).where(bank_account: params[:bank]) if params[:bank] && !params[:bank].empty?
    @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).where(fund_type: params[:fund_type]) if params[:fund_type] && !params[:fund_type].empty?
    if params[:lock]
      @contribution_transaction.update_all(editable: false)
    end
    if params[:unlock]
      @contribution_transaction.update_all(editable: true)
    end
    respond_to do |format|
      format.html{
        @contribution_transactions = @contribution_transaction.paginate(page: params[:page], per_page: 30)
      }
      format.csv {
        send_data generate_contribution_transactions_csv(@contribution_transaction)
      }
    end
  end

  def tpri
    @contribution_transaction = ContributionTransaction.where(bank_account: "TPRI")
    @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).where(member: Member.search(params[:name])) if params[:name] && !params[:name].empty?
    if params[:fund_type] && !params[:fund_type].empty? && params[:fund_type] == "special_contribution"
      @contribution_transaction = @contribution_transaction.query_by_month2(params[:year]) if params[:year] && !params[:year].empty?
      @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).query_by_year(params[:year]) if params[:year] && !params[:year].empty?
    else
      @contribution_transaction = @contribution_transaction.query_by_year2(params[:month]) if params[:month] && !params[:month].empty?
      @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).query_by_month2(params[:month]) if params[:month] && !params[:month].empty?
    end
    @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).where(bank_account: params[:bank]) if params[:bank] && !params[:bank].empty?
    @contribution_transaction = @contribution_transaction.order(bank_statement_date: :desc).where(fund_type: params[:fund_type]) if params[:fund_type] && !params[:fund_type].empty?

    respond_to do |format|
      format.html{
        @contribution_transactions = @contribution_transaction.paginate(page: params[:page], per_page: 30)
      }
      format.csv {
        send_data generate_tpri_csv(@contribution_transaction)
      }
    end

  end

  def member
    @sectors = Sector.where(active: true).pluck(:id)
    @contribution_transaction = ContributionTransaction.all
    @contribution_transaction = @contribution_transaction.where(fund_type: params[:fund_type]) if params[:fund_type] && !params[:fund_type].empty?
    if params[:fund_type] && !params[:fund_type].empty? && params[:fund_type] == "special_contribution"
      @contribution_transaction = @contribution_transaction.query_by_year(params[:month]) if params[:month] && !params[:month].empty?
    else
      @contribution_transaction = @contribution_transaction.query_by_month(params[:month]) if params[:month] && !params[:month].empty?
    end

    @contribution_transactions = @contribution_transaction.where(late_pay: true) if params[:condition] && params[:condition]=="late_pay"
    @contribution_transactions = @contribution_transaction if params[:condition] && params[:condition]=="no_pay"
    # byebug
    if params[:condition] && params[:condition]=="late_pay"
      members_id = @contribution_transactions.pluck(:member_id)
    elsif params[:condition] && params[:condition]=="no_pay"
      members_id = Member.where(on_behalf: false).pluck(:id) - @contribution_transactions.pluck(:member_id)
    else
      members_id = Member.where(on_behalf: false).pluck(:id)
    end
    @members = Member.includes(:contribution_transactions, :sector, :pledges).where(id: members_id)
    @members = @members.search(params[:name]) if params[:name] && !params[:name].empty?
    if params[:reminder] == 'true' && params[:condition] == 'no_pay' && params[:month] && !params[:month].empty?
      @members.each do |member|
        if member.email && !member.email.empty?
          month = params[:month]
          UserNotifierMailer.send_reminder(member, month).deliver_later!
        end
      end
    end
    respond_to do |format|
      format.html{
        @members = @members.order(:sector_id, :gender).sort_by{ |x| x.sector.id }.paginate(page: params[:page], per_page: 30)
      }
      format.csv {
        @members = @members.order(:sector_id, :gender).select { |x| @sectors.include?(x.sector_id.to_i)}
        send_data generate_nongivers_csv(@members)
      }
    end
  end

  def summary
    if params[:condition] && params[:condition]=="late_pay"
      members_id = @contribution_transactions.pluck(:member_id)
    elsif params[:condition] && params[:condition]=="no_pay"
      members_id = Member.pluck(:id) - @contribution_transactions.pluck(:member_id)
    else
      members_id = Member.pluck(:id)
    end
    @member = Member.includes(:contribution_transactions, :sector, :pledges).where(id: members_id, sector_id: [1,2,4,5,6,7,15,17,18], on_behalf: false)
    @memberTotal = Member.includes(:contribution_transactions, :sector, :pledges).where(id: members_id, sector_id: [1,2,4,5,6,7,15,17,18])
    @membersTotal = @memberTotal.group_by(&:sector_id)

    @members = @member.group_by(&:sector_id)

    year = (params[:month] && !params[:month].empty?) ? params[:month].to_date.year.to_s : Date.today.year.to_s
    month = (params[:month] && !params[:month].empty?) ? params[:month].to_date : Date.today.to_date

    @pledges = []
    @monthContributionNotGiven = []
    @buildingFundNotGiven = []
    @members.keys.each do |key|
      total = 0
      totalPledgesNotGiven = 0
      totalBuildingFundNotGiven = 0
      @members[key].each do |member|
        range = (("1/1/"+year).to_date.beginning_of_year..month.end_of_month)
        my_pledge = member.pledges.select{ |x| range.cover?x.year }.pluck(:amount).sum
        if member.pledges.select{ |x| range.cover?x.year }.length == 0
          my_pledge = member.pledges.last.amount if member.pledges.last
          my_pledge = 0 unless member.pledges.last
        end
        my_building_fund = member.pledges.select{ |x| range.cover?x.year }.pluck(:building_fund_pledge).sum
        if member.pledges.select{ |x| range.cover?x.year }.length == 0
          my_building_fund = member.pledges.last.building_fund_pledge if member.pledges.last
          my_building_fund = 0 unless member.pledges.last
        end

        total = total + my_pledge
        myTransactions = member.contribution_transactions.select{ |x| x.fund_type == "contribution"}.select{ |x| range.cover?x.transaction_date}.pluck(:amount)
        if myTransactions.length < month.month
          outstandingMonths = (month.month - myTransactions.length) * my_pledge
          totalPledgesNotGiven += outstandingMonths
        end

        myBuildingFunds = member.contribution_transactions.select{ |x| x.fund_type == "building_fund"}.select{ |x| range.cover?x.transaction_date}.pluck(:building_fund_pledge)
        if myBuildingFunds.length < month.month
          outstandingBuilding = (month.month - myBuildingFunds.length) * my_building_fund
          totalBuildingFundNotGiven += outstandingBuilding
        end
      end
      @pledges.append(total)

app/helpers/contribution_transactions_helper.rb
module ContributionTransactionsHelper
end

app/views/contribution_transactions/index.html.erb
<% provide(:title, "Contribution Transactions List") %>

<p id="notice"><%= notice %></p>

<%= form_tag(contribution_transactions_path, :method => "get", id: "search-form") do %>
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-md-offset-2">
        <%= text_field_tag :paid_by, params[:paid_by], placeholder: "Search Paid By", id: 'search_field' %>
      </div>
      <div class="col-md-3">
        <%= text_field_tag :name, params[:name], placeholder: "Search Member", id: 'search_field' %>
      </div>
      <div class="col-md-3">
        <%= text_field_tag :month, params[:month], placeholder: "Search For Which Month", id: 'select_month' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 col-md-offset-2">
        <%= text_field_tag :bank_statement, params[:bank_statement], placeholder: "Search Bank Statement Date", id: 'select_bank' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3  col-md-offset-2">
        <%= select_tag :bank,options_for_select(
          ContributionTransaction::BANK_ACCOUNT, params[:bank] || ''
        ), {class: "form-control" , prompt: 'Bank Account'}  %>

      </div>
      <div class="col-md-3">
        <%= select_tag :fund_type,options_for_select(
          ContributionTransaction::FUND_TYPE, params[:fund_type] || ''
        ), {class: "form-control" , prompt: 'Fund Type'}  %>
      </div>

      <div class="col-md-3">
        <%= select_tag :sector, options_for_select(Sector.options_for_select_type, params[:sector]),
         {class: "form-control" , prompt: 'Fund Type', include_blank: true, id: 'select_sector', prompt: 'Filter Sector' }  %>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-5 col-md-offset-4">
        <div class="col-md-3">
          <%= submit_tag "Filter", id: 'searchBtn',  class: 'btn filter btn-info' %>
        </div>
        <div class="col-md-3">
          <%= submit_tag "Lock", id: 'searchBtn',  class: 'btn filter btn-danger', name: 'lock' %>
        </div>
        <div class="col-md-3">
          <%= submit_tag "Unlock", id: 'searchBtn',  class: 'btn filter btn-danger', name: 'unlock', data: { confirm: 'Be CAREFUL with printed TPRI Receipts!!' } %>
        </div>
      </div>
    </div>
  </div>
<% end %>


<h1>Contribution Transactions List</h1>

<%= link_to 'New Contribution Transaction', new_contribution_transaction_path(name: params[:name], bank: params[:bank],
      month: params[:month], fund_type: params[:fund_type]), class: 'btn btn-primary' %> &nbsp;
<%= link_to 'Download CSV', contribution_transactions_path(format: 'csv', name: params[:name], bank: params[:bank], month: params[:month], fund_type: params[:fund_type], paid_by: params[:paid_by], sector: params[:sector]), class: 'btn btn btn-primary' %> <br> <br>
<div id="no-more-tables">
  <table id="table_id" class="col-md-12 table-bordered table-condensed cf display">
    <thead>
      <tr>
        <th>Paid By</th>
        <th>Member</th>
        <th>For which Month?</th>
        <th>Bank statement date</th>
        <th>Bank Account</th>
        <th>Fund Type</th>
        <th>Amount</th>
        <th>Comment</th>
        <th>Created At</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @contribution_transactions.each do |contribution_transaction| %>
        <tr>
          <td><%= contribution_transaction.paid_by.common_name %></td>
          <td><%= contribution_transaction.member.common_name %></td>
          <td><%= contribution_transaction.transaction_date.strftime("%B") %></td>
          <td><%= contribution_transaction.bank_statement_date.strftime("%d/%m/%Y") %></td>
          <td><%= contribution_transaction.bank_account %></td>
          <td><%= ContributionTransaction::FUND_TYPE_NAME[contribution_transaction.fund_type] %></td>
          <td><%= '%.2f' % contribution_transaction.amount %></td>
          <td><%= contribution_transaction.comment %></td>
          <td>
            <%= form_for(contribution_transaction) do |f| %>
                <div class="col-md-6" style="display: block; valign: middle;">
                  <%= f.datetime_field :created_at %>
                </div>

              <div class="actions" style="display: inline-block; valign: middle;">
              <%= f.submit "Update" %>
            <% end %>
          </td>
          <td><%= link_to 'Show', contribution_transaction %> ||
              <%= link_to contribution_transaction.editable ? "Edit" : "View", edit_contribution_transaction_path(contribution_transaction) %> ||
              <%= link_to 'Destroy', contribution_transaction, class: 'delete', method: :delete, data: { confirm: 'Are you sure?' } if contribution_transaction.editable %>
              <% unless contribution_transaction.editable %>
                <i class="fas fa-lock"></i>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
<%= will_paginate @contribution_transactions %>



<script>
$("#select_month").datepicker( {
    format: "mm/yyyy",
    viewMode: "months",
    minViewMode: "months",
    autoclose: true
});
$("#select_bank").datepicker( {
    format: "mm/yyyy",
    viewMode: "months",
    minViewMode: "months",
    autoclose: true
});

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-90556377-1', 'auto');
ga('send', 'pageview');

</script>

app/views/contribution_transactions/member2.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(contribution_transactions_member_path, :method => "get", id: "search-form") do %>
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-md-offset-3">
        <%= text_field_tag :name, params[:name], placeholder: "Search Name", id: 'search_field' %>
      </div>
      <div class="col-md-3 col-md-offset-4">
        <%= date_field_tag :month, params[:month], id: 'select_month' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 col-md-offset-4">
        <%= select_tag :condition, options_for_select(
          [['Select Status', ''], ['No Records', 'no_pay'], ['Late Givers', 'late_pay']], params[:condition] || ''
        ), {class: "form-control" }  %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 col-md-offset-4">
        <%= select_tag :fund_type, options_for_select(
          ContributionTransaction::FUND_TYPE, params[:fund_type] || ''
        ), {class: "form-control" }  %>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-3 col-md-offset-4">
      <%= submit_tag "Filter", id: 'searchBtn', style: 'margin-top: 10px;' %>
      </div>
    </div>
  </div>
<% end %>

<h1>Member's Contribution Report</h1>

<%= link_to 'New Contribution Transaction', new_contribution_transaction_path %> &nbsp; || &nbsp;
<%= link_to ' Contribution Transaction', contribution_transactions_path %> &nbsp; || &nbsp;
<%= link_to 'Pledges', pledges_path %>
<br>
<div id="no-more-tables">
<table id="table_id" class="col-md-12 table-bordered table-condensed cf display">
  <thead>
    <tr>
      <th rowspan="3" style="text-align:center;">No.</th>
      <th rowspan="3" style="text-align:left;">Name</th>
      <th rowspan="3">Sector</th>
      <th rowspan="2" colspan="2" style="text-align:center;">Pledged Amount</th>
      <th colspan="4" style="text-align:center;">January</th>
      <th colspan="4" style="text-align:center;">February</th>
      <th colspan="4" style="text-align:center;">March</th>
      <th colspan="4" style="text-align:center;">April</th>
      <th colspan="4" style="text-align:center;">May</th>
      <th colspan="4" style="text-align:center;">June</th>
      <th colspan="4" style="text-align:center;">July</th>
      <th colspan="4" style="text-align:center;">August</th>
      <th colspan="4" style="text-align:center;">September</th>
      <th colspan="4" style="text-align:center;">October</th>
      <th colspan="4" style="text-align:center;">November</th>
      <th colspan="4" style="text-align:center;">December</th>
      <th colspan="4" style="text-align:center;">Total</th>
      <th rowspan="3" style="text-align:center;"></th>
      <th rowspan="2" colspan="4" style="text-align:center;">Special Contribution</th>
    </tr>
    <tr>
      <th colspan="2"> Contribution </th>
      <th colspan="2"> Building Fund </th>
      <th colspan="2"> Contribution </th>
      <th colspan="2"> Building Fund </th>
      <th colspan="2"> Contribution </th>
      <th colspan="2"> Building Fund </th>
      <th colspan="2"> Contribution </th>
      <th colspan="2"> Building Fund </th>
      <th colspan="2"> Contribution </th>
      <th colspan="2"> Building Fund </th>
      <th colspan="2"> Contribution </th>
      <th colspan="2"> Building Fund </th>
      <th colspan="2"> Contribution </th>
      <th colspan="2"> Building Fund </th>
      <th colspan="2"> Contribution </th>
      <th colspan="2"> Building Fund </th>
      <th colspan="2"> Contribution </th>
      <th colspan="2"> Building Fund </th>
      <th colspan="2"> Contribution </th>
      <th colspan="2"> Building Fund </th>
      <th colspan="2"> Contribution </th>
      <th colspan="2"> Building Fund </th>
      <th colspan="2"> Contribution </th>
      <th colspan="2"> Building Fund </th>
      <th colspan="2"> Contribution </th>
      <th colspan="2"> Building Fund </th>
    </tr>
    <tr>
      <!-- <th colspan="3">  </th> -->
      <th style="text-align:center;"> Contribution </th>
      <th style="text-align:center;"> Building Fund </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> Pledged </th>
      <th style="text-align:center;"> TPRI </th>
      <th style="text-align:center;"> CCCOM </th>
      <th style="text-align:center;"> Outstanding </th>
    </tr>
  </thead>

  <tbody>
    <% @year = (params[:year] && !params[:year].empty) ? params[:year].to_s : Date.today.year.to_s %>
    <% @members.each_with_index do |member, index| %>
      <tr>
        <td> <%= @members.offset + index + 1 %></td>
        <td> <%= member.common_name %> </td>
        <td> <%= member.sector ? member.sector.sector_type : '' %> </td>
        <td style="text-align:center;">

          <% @range = (("1/1/"+@year).to_date.beginning_of_year..("1/1/"+@year).to_date.end_of_year) %>
          <%= '%.2f' % member.pledges.select{ |x|                   @range.cover?x.year}.pluck(:amount).sum %>
        </td>
        <td style="text-align:center;">

          <% @range = (("1/1/"+@year).to_date.beginning_of_year..("1/1/"+@year).to_date.end_of_year) %>
          <%= '%.2f' % member.pledges.select{ |x|                   @range.cover?x.year}.pluck(:building_fund_pledge).sum %>
        </td>


        <td>

          <%= link_to contribution_transactions_path(name: member.common_name, month: ('1/1/' + @year), fund_type: "contribution", bank: "TPRI") do %>

            <% @range = (("1/1/"+@year).to_date.beginning_of_month..("1/1/"+@year).to_date.end_of_month) %>
            <%= '%.2f' % member.contribution_transactions.reject{ |x| (x.fund_type == "building_fund" || x.fund_type == "special_contribution")}.select{ |x| x.bank_account == "TPRI"}.select{ |x| @range.cover?x.transaction_date}.pluck(:amount).sum %>

            <% @range = (("1/1/"+@year).to_date.beginning_of_month..("1/1/"+@year).to_date.end_of_month) %>
            <%= '%.2f' % member.contribution_transactions.select{ |x| x.bank_account == "TPRI" && x.fund_type == "building_fund"}.select{ |x| @range.cover?x.transaction_date}.pluck(:amount).sum %>


          <% end %>
        </td>



        <%= link_to contribution_transactions_path(name: member.common_name, month: ('1/1/' + @year), fund_type: "contribution", bank: "CCCOM") do %>
          <%= '%.2f' % member.contribution_transactions.where.not(fund_type: "building_fund", fund_type: "special_contribution").where(bank_account: "CCCOM").query_by_month('1/1/2017').pluck(:amount).sum %>
        <% end %>



      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= will_paginate @members %>

<br>

<%= link_to 'New Contribution Transaction', new_contribution_transaction_path %>

app/views/contribution_transactions/new.html.erb
<% provide(:title, "New Contribution") %>
<h1>New Contribution Transaction</h1>
<div class="row">
  <%= render 'form', contribution_transaction: @contribution_transaction %>
</div>
<div class="row center">
<%= link_to 'Back', contribution_transactions_path %>
</div>