config/routes.rb
Rails.application.routes.draw do

  resources :main_sectors
  resources :absentees
  resources :pledges
  resources :contribution_transactions
  devise_for :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'members#new'
  get  '/members/pledge_amount_query',  to: 'members#query_for_pledge_amount', as: :pledge_amount_query
  get  '/members/pledge_amount_percentage_query',  to: 'members#query_for_pledge_percentage', as: :pledge_amount_percentage_query
  get  '/members/pledge_building_fund_pledge_query',  to: 'members#query_for_pledge_building_fund', as: :pledge_building_fund_pledge_query
  get  '/members/pledge_special_contribution_pledge_query',  to: 'members#query_for_pledge_special_contribution', as: :pledge_special_contribution_pledge_query
  get  '/members/pledge_last_pledge_query',  to: 'members#query_for_last_pledge', as: :pledge_last_pledge_query
  get  '/members/contribution_transactions',  to: 'members#query_for_contribution_transactions', as: :contribution_transactions_query
  get  '/members/member_groups',  to: 'members#query_for_member_groups', as: :member_groups_query
  get  '/members/indexall', to: 'members#indexall'
  get  '/contribution_transactions_member', to: 'contribution_transactions#member'
  get  '/my_contribution_transactions_member', to: 'contribution_transactions#member_records'
  get  '/contribution_transactions_summary', to: 'contribution_transactions#summary'
  get  '/contribution_transactions_summary2', to: 'contribution_transactions#summary2'
  get  '/contribution_transactions_summary3', to: 'contribution_transactions#summary3'
  get  '/contribution_transactions_summary4', to: 'contribution_transactions#summary4'
  get  '/contribution_transactions_bank_summary', to: 'contribution_transactions#bank_summary'
  get  '/contribution_transactions_tpri', to: 'contribution_transactions#tpri'
  get  '/pledges_member', to: 'pledges#member'
  get  '/absent_report', to: 'absentees#absent_report'

  resources :members do
    get :member_group
    get :create_member_group
    get :add_member_group
    get :delete_member_group
    collection do
      post :import
    end
  end
  resources :staffs
  resources :sectors
  resources :sector_transactions

  devise_scope :user do
     get 'logout', :to => 'devise/sessions#destroy'
  end
end

app/views/layouts/_footer.html.erb
<div class="clearfix"></div>
<footer class="footer">
  <small>
    Central Christian Church of Malaysia
  </small>
  <nav>
    <ul>
      <!-- <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li> -->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container" style="width: 90%;">
    <%= image_tag "logo.jpg", class: 'navbar-brand' %>
    <%= link_to "Central Christian Church of Malaysia", root_path, id: "logo" %>

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown">Staffs</a>
            <ul class="dropdown-menu">
              <li><%= link_to "Membership", members_path %></li>
              <li><%= link_to "Report", sector_transactions_path %></li>
              <li><%= link_to "Sectors", sectors_path %></li>
              <li><%= link_to "Sector Contribution Report", my_contribution_transactions_member_path %></li>
              <li><%= link_to "Contribution Summary", contribution_transactions_summary_path %></li>
            </ul>
          </li>
          <% if current_user.admin %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown">Admin</a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "Members Contribution Report", contribution_transactions_member_path %>
                </li>
                <li>
                  <%= link_to "Contribution Transactions List", contribution_transactions_path %>
                </li>
                <li>
                  <%= link_to "Pledges Report", pledges_member_path %>
                </li>
                <li>
                  <%= link_to "Pledges List", pledges_path %>
                </li>
                <li>
                  <%= link_to "TPRI Report", contribution_transactions_tpri_path %>
                </li>
                <li>
                  <%= link_to "Bank Account Summary", contribution_transactions_bank_summary_path %>
                </li>
              </ul>
            </li>
          <% end %>
          <li>
            <% link_to "Absentee Report", absentees_path %>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown">Account</a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <li><%= link_to "Log Out", logout_path %></li>
            </ul>
          </li>
        <% else %>
        <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<script>
  $('.dropdown-toggle').dropdown();
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">


    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" style="width: 90%;">
      <% if alert %>
      <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>

    </div>
  </body>
</html>