config/routes.rb
Rails.application.routes.draw do

  resources :main_sectors
  resources :absentees
  resources :pledges
  resources :contribution_transactions
  devise_for :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'members#new'
  get  '/members/pledge_amount_query',  to: 'members#query_for_pledge_amount', as: :pledge_amount_query
  get  '/members/pledge_amount_percentage_query',  to: 'members#query_for_pledge_percentage', as: :pledge_amount_percentage_query
  get  '/members/pledge_building_fund_pledge_query',  to: 'members#query_for_pledge_building_fund', as: :pledge_building_fund_pledge_query
  get  '/members/pledge_special_contribution_pledge_query',  to: 'members#query_for_pledge_special_contribution', as: :pledge_special_contribution_pledge_query
  get  '/members/pledge_last_pledge_query',  to: 'members#query_for_last_pledge', as: :pledge_last_pledge_query
  get  '/members/contribution_transactions',  to: 'members#query_for_contribution_transactions', as: :contribution_transactions_query
  get  '/members/member_groups',  to: 'members#query_for_member_groups', as: :member_groups_query
  get  '/members/indexall', to: 'members#indexall'
  get  '/contribution_transactions_member', to: 'contribution_transactions#member'
  get  '/my_contribution_transactions_member', to: 'contribution_transactions#member_records'
  get  '/contribution_transactions_summary', to: 'contribution_transactions#summary'
  get  '/contribution_transactions_summary2', to: 'contribution_transactions#summary2'
  get  '/contribution_transactions_summary3', to: 'contribution_transactions#summary3'
  get  '/contribution_transactions_summary4', to: 'contribution_transactions#summary4'
  get  '/contribution_transactions_bank_summary', to: 'contribution_transactions#bank_summary'
  get  '/contribution_transactions_tpri', to: 'contribution_transactions#tpri'
  get  '/pledges_member', to: 'pledges#member'
  get  '/absent_report', to: 'absentees#absent_report'

  resources :members do
    get :member_group
    get :create_member_group
    get :add_member_group
    get :delete_member_group
    collection do
      post :import
    end
  end
  resources :staffs
  resources :sectors
  resources :sector_transactions

  devise_scope :user do
     get 'logout', :to => 'devise/sessions#destroy'
  end
end

app/models/member.rb
require 'csv'

class Member < ApplicationRecord

  before_save { self.ic_name = ic_name.titleize }
  before_save { self.common_name = common_name.titleize }
  # has_many :contributions, dependent: :destroy
  belongs_to :leader, class_name: 'Member', foreign_key: 'leader_id', optional: true, inverse_of: :members
  belongs_to :member_group_leader, class_name: 'Member', foreign_key: 'member_group_id', optional: true, inverse_of: :members
  belongs_to :previous_leader, class_name: 'Member', foreign_key: 'previous_leader_id', optional: true
  belongs_to :current_leader, class_name: 'Member', foreign_key: 'current_leader_id', optional: true
  belongs_to :sector, -> { order(id: :asc)}

  has_many :contribution_transactions
  has_many :pledges
  has_many :ct_receipt_to, class_name: 'ContributionTransaction', foreign_key: 'receipt_to_id'
  has_many :ct_paid_for, class_name: 'ContributionTransaction', foreign_key: 'paid_by_id'
  has_many :members, class_name: 'Member', foreign_key: 'leader_id', inverse_of: :leader
  has_many :member_groups, class_name: 'Member', foreign_key: 'member_group_id', inverse_of: :member_group_leader
  validates :ic_name, presence: true
  validates :common_name, presence: true
  validates :ic_no, presence: true
  validates :d_o_b, presence: true
  validates :baptism_date, presence: true

  def self.search(search)
    where("common_name ILIKE '%#{search}%' OR ic_name ILIKE '%#{search}%'")
  end

  def self.filter_out_on_behalf()
    where(on_behalf: false)
  end

  def self.search_by_sector(search)
    where(sector: Sector.search(search).first)
  end

  def self.search_by_leader(search)
    where(leader: Member.find_by(id: search))
  end

  def self.options_for_select_type
    order('LOWER(common_name)').map { |e| e.is_leader ? [e.common_name, e.id] : nil }.compact
  end

  def self.query_for_pledge_amount(id)
    a = where(id: id).last
    a.pledges.last ? a.pledges.order(year: :desc).last.amount : nil
  end

  def self.query_for_pledge_percentage(id)
    a = where(id: id).last
    a.pledges.last ? a.pledges.order(year: :desc).last.amount_percentage : nil
  end

  def self.query_for_building_fund(id)
    a = where(id: id).last
    a.pledges.last ? a.pledges.order(year: :desc).last.building_fund_pledge : nil
  end

  def self.query_for_special_contribution(id)
    a = where(id: id).last
    a.pledges.last ? a.pledges.order(year: :desc).last.special_contribution_pledge : nil
  end

  def self.query_for_last_pledge(id)
    a = where(id: id).last
    a.pledges.order(year: :desc).first
  end

  def self.import(file)
    spreadsheet = Roo::Spreadsheet.open(file.path)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      member = find_by(id: row["id"]) || new
      member.attributes = row.to_hash
      member.save!
    end
  end

  def self.to_csv(options = {})
  desired_columns = ["ic_name", "common_name", "ic_no", "handphone", "is_leader", "gender", "leader_id", "sector_id"]
    CSV.generate(options) do |csv|
      csv << desired_columns
      all.each do |member|
        gender = member.gender ? "Male" : "Female"
        is_leader = member.is_leader ? "Yes" : "No"
        leader_id = member.leader ? member.leader.common_name : ''
        sector_id = member.sector ? member.sector.sector_type : ''
        csv << [member.ic_name, member.common_name, member.ic_no, member.handphone, is_leader, gender, leader_id, sector_id]
      end
    end
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  include ApplicationHelper
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /members
  # GET /members.json
  def index
    @members = Member.all.includes(:sector, :leader)
    @members = @members.search_by_leader(params[:leader]) if params[:leader] && !params[:leader].empty?
    @members = @members.search(params[:search]) if params[:search] && !params[:search].empty?
    @members = @members.search_by_sector(params[:sector]) if params[:sector] && !params[:sector].empty?
    @members = @members.where(gender: params[:gender]) if params[:gender] && !params[:gender].empty?
    @members = @members.where(on_behalf: params[:on_behalf]) if params[:on_behalf] && !params[:on_behalf].empty?
    @members = @members.where(esi: params[:esi]) if params[:esi] && !params[:esi].empty?
    @members = @members.where(tpri: params[:tpri]) if params[:tpri] && !params[:tpri].empty?
    @members = @members.order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)


    respond_to do |format|
      format.html{
        @members = @members.paginate(page: params[:page], per_page: 50)
      }
      format.csv {
        @members = @members.order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
        send_data generate_member_csv(@members)
      }
      format.xls
    end

  end

  def indexall

    if params[:search] && params[:sector] && params[:leader] && !params[:sector].empty? && !params[:leader].empty?
      @members = Member.paginate(page: params[:page], per_page: 50).search_by_leader(params[:leader]).search(params[:search]).search_by_sector(params[:sector]).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
    elsif params[:search] && params[:sector] && !params[:sector].empty?
      @members = Member.paginate(page: params[:page], per_page: 50).search(params[:search]).search_by_sector(params[:sector]).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
    elsif params[:search] && params[:leader] && !params[:leader].empty?
      @members = Member.paginate(page: params[:page], per_page: 50).search(params[:search]).search_by_leader(params[:leader]).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
    elsif params[:search]
      @members = Member.paginate(page: params[:page], per_page: 50).search(params[:search]).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
    else
      @members = Member.paginate(page: params[:page], per_page: 50).all.includes(:sector, :leader).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
    end

    respond_to do |format|
      format.html{
        if params[:search] && params[:sector] && params[:leader] && !params[:sector].empty? && !params[:leader].empty?
          @members = Member.paginate(page: params[:page], per_page: 50).search_by_leader(params[:leader]).search(params[:search]).search_by_sector(params[:sector]).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
        elsif params[:search] && params[:sector] && !params[:sector].empty?
          @members = Member.paginate(page: params[:page], per_page: 50).search(params[:search]).search_by_sector(params[:sector]).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
        elsif params[:search] && params[:leader] && !params[:leader].empty?
          @members = Member.paginate(page: params[:page], per_page: 50).search(params[:search]).search_by_leader(params[:leader]).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
        elsif params[:search]
          @members = Member.paginate(page: params[:page], per_page: 50).search(params[:search]).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
        else
          @members = Member.all.includes(:sector, :leader).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc).sort_by{ |x| x.sector.id }.paginate(page: params[:page], per_page: 50)
        end
      }

      format.csv {

        if params[:search] && params[:sector] && params[:leader] && !params[:sector].empty? && !params[:leader].empty?
          @members = Member.search_by_leader(params[:leader]).search(params[:search]).search_by_sector(params[:sector]).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
        elsif params[:search] && params[:sector] && !params[:sector].empty?
          @members = Member.search(params[:search]).search_by_sector(params[:sector]).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
        elsif params[:search] && params[:leader] && !params[:leader].empty?
          @members = Member.search(params[:search]).search_by_leader(params[:leader]).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
        elsif params[:search]
          @members = Member.search(params[:search]).order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
        else
          @members = Member.all.order(:sector_id, :leader_id, gender: :desc, is_leader: :desc)
        end
        send_data @members.to_csv
      }
      format.xls
    end

  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      my_member_params = member_params
      my_member_params[:sector_id] = member_params[:sector_id].empty? ? @member.sector_id : member_params[:sector_id]
      if @member.sector_id != my_member_params[:sector_id].to_i && (@member.sector.users.pluck(:id).include?(current_user.id) || current_user.admin)
        @sector_transaction = SectorTransaction.create(previous_sector_id: @member.sector.id, current_sector_id: my_member_params[:sector_id], member: @member)
        UserNotifierMailer.send_notification(@member, @sector_transaction, Sector.find_by(id: my_member_params[:sector_id]).users.pluck(:email)).deliver
        my_member_params[:leader_id] = nil
      end
      if (@member.sector.users.pluck(:id).include?(current_user.id) || current_user.admin)  && @member.update(my_member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { redirect_to @member, notice: "You are not authorized to edit #{@member.common_name}, please contact the Staff in charge" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
      respond_to do |format|
        if (@member.sector && @member.sector.users.pluck(:id).include?(current_user.id) || current_user.admin) && @member.destroy
        format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to members_path, notice: "You are not authorized to delete #{@member.common_name}, please contact the Staff in charge" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def member_group
    @member = Member.find(params[:member_id])
    @members = Member.includes(:sector)
  end

  def create_member_group
    @member = Member.find(params[:member_id])
    unless @member.member_groups.include?(@member)
      @member.member_groups << @member
    end
    redirect_to member_member_group_path(@member)
  end

  def add_member_group
    @member = Member.find(params[:member_id])
    @new_member = Member.find(params[:new_member_id])
    unless @member.member_groups.include?(@new_member)
      @member.member_groups << @new_member
    end
    redirect_to member_member_group_path(@member)
  end

  def delete_member_group
    @member = Member.find(params[:member_id])
    @mgi = @member.member_group_id
    @mm = Member.find(@mgi)
    @member.member_group_id = nil
    @member.save
    redirect_to member_member_group_path(@mm)
  end

  def import
    Member.import(params[:file])
    redirect_to members_path, notice: 'Data imported.'
  end

  def query_for_pledge_amount
    amount = nil
    if params[:id] && !params[:id].empty?
      amount = Member.query_for_pledge_amount(params[:id])
    end
    render json: { pledge_amount: amount }
  end

  def query_for_pledge_percentage
    amount = nil
    if params[:id] && !params[:id].empty?
      amount = Member.query_for_pledge_percentage(params[:id])
    end
    render json: { pledge_percentage: amount }
  end

  def query_for_pledge_building_fund
    amount = nil
    if params[:id] && !params[:id].empty?
      amount = Member.query_for_building_fund(params[:id])
    end
    render json: { pledge_building_fund: amount }
  end

  def query_for_pledge_special_contribution
    amount = nil
    if params[:id] && !params[:id].empty?
      amount = Member.query_for_special_contribution(params[:id])
    end
    render json: { pledge_special_contribution: amount }
  end

  def query_for_last_pledge
    pledge = nil
    if params[:id] && !params[:id].empty?
      pledge = Member.query_for_last_pledge(params[:id])
    end
    render json: { last_pledge: pledge }
  end

  def query_for_member_groups
    groups = nil
    if params[:id] && !params[:id].empty?
      member = Member.find(params[:id])
      groups = []
      if member.member_group_leader
        group_array = member.member_group_leader.member_groups
        group_array.each do |m|

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/edit.html.erb
<% provide(:title, "Members Edit") %>
<p id="notice"><%= notice %></p>

<h1>Editing Member</h1>
Fields marked with an * are compulsory
<%= render 'form2', member: @member %>


<div class="actions center">
  <%= link_to 'Show', @member, class: 'btn btn btn-primary' %> &nbsp;
  <%= link_to 'Back', members_path, class: 'btn btn btn-primary' %>
</div>

<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-90556377-1', 'auto');
ga('send', 'pageview');
</script>

app/views/members/index.html.erb
<% provide(:title, "Members Index") %>
<p id="notice"><%= notice %></p>
<!-- <div style="width: 15%;">
  <h2>Import Data</h2>
  <%= form_tag import_members_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
  <% end %>
</div> -->
  <%= form_tag(members_path, :method => "get", id: "search-form") do %>
    <div style="width: 45%;">
      <%= text_field_tag :search, params[:search], placeholder: "Search Members", id: 'search_field' %>
    </div>
    <div class="row">
      <div style="margin-bottom: 10px; width: 15%; float:left;">
        <%= select_tag :sector, options_for_select(Sector.options_for_select_type, params[:sector]), include_blank: true, id: 'select_sector', prompt: 'Filter Sector' %>
      </div>
      <div style="width: 15%; float:left;">
        <%= select_tag :leader, options_for_select(Member.options_for_select_type, params[:leader]), include_blank: true, id: 'select_leader', prompt: 'Filter Bibletalk Leader' %>
      </div>
      <div style="width: 15%; float:left;">
        <%= select_tag :gender, options_for_select([["Male", true], ["Female", false]], params[:gender]), include_blank: true, id: 'select_gender', prompt: 'Filter by Gender' %>
      </div>
    </div>
    <div class="row">
      <div style="width: 15%; float:left;">
        <%= select_tag :on_behalf, options_for_select([["Yes", true], ["No", false]], params[:on_behalf]), include_blank: true, id: 'select_on_behalf', prompt: 'Filter Unemployed/No job' %>
      </div>
      <div style="width: 15%; float:left;">
        <%= select_tag :esi, options_for_select([["Yes", true], ["No", false]], params[:esi]), include_blank: true, id: 'select_esi', prompt: 'Filter ESI' %>
      </div>
      <div style="width: 15%; float:left;">
        <%= select_tag :tpri, options_for_select([["Yes", true], ["No", false]], params[:tpri]), include_blank: true, id: 'select_tpri', prompt: 'Filter TPRI' %>
      </div>
    </div>
    <div style="width: 10%;">
    <%= submit_tag "Search", :name => nil, id: 'searchBtn', style: 'margin-top: 10px;', class: 'btn filter btn-info' %>
    <% end %>
    </div>
    <br>
    <div>Total Queried: <%= @members.count %></div>

  <% if @members.blank? %>
    <h4>There are no names that fits the search/filter.</h4>
  <% else %>

  <h1>Members</h1>
  <%= link_to 'New Member', new_member_path, class: 'btn btn btn-primary' %> &nbsp;
  <%= link_to 'Show All Details', members_indexall_path, class: 'btn btn btn-primary' %> &nbsp;
  <%= link_to "Download CSV", members_path(format: "csv", search: params[:search], leader: params[:leader], sector: params[:sector], gender: params[:gender], esi: params[:esi], on_behalf: params[:on_behalf], tpri: params[:tpri]), class: 'btn btn btn-primary' %>

  <br><br>
  <!-- <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.css">
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.js"></script> -->

  <div id="no-more-tables">
    <table id="table_id" class="col-md-12 table-bordered table-condensed cf display">
    <thead class="cf">
      <tr>
        <th>ID</th>
        <th>Common Name</th>
        <th>Ic Name</th>
        <th>IC Number</th>
        <th>Handphone Number</th>
        <th>Gender</th>
        <th>Sector</th>
        <th>Leadership?</th>
        <th>Leader's Name</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @members.select{|x| x.sector.active}.sort_by{|x| x.sector_id}.each do |member| %>
        <tr style="<%= 'background-color:#EBF5FB;' if member.gender == true %><%= 'background-color:#FDEDEC;' if member.gender == false %>">
          <td><%= member.id %></td>
          <td><%= member.common_name %></td>
          <td><%= member.ic_name %></td>
          <td><%= member.ic_no %></td>
          <td><%= member.handphone%></td>
          <td><%= member.gender ? "Male" : "Female" %></td>
          <td><%= member.sector ? member.sector.sector_type : '' %></td>
          <td><%= member.is_leader ? "Yes" : "No" %></td>
          <td><%= member.leader ? member.leader.common_name : '' %></td>
          <td><%= link_to 'Show', member %> ||
              <%= link_to 'Edit', edit_member_path(member) %>&nbsp; ||
              <%= link_to 'Delete', member, class: 'delete', method: :delete, data: { confirm: 'Delete entry from SECTOR TRANSACTIONS first!!' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  <%= will_paginate @members %>
<% end %>
&nbsp;
<script>
  $('#select_sector, #select_leader, #select_gender, #select_on_behalf, #select_esi, #select_tpri').change(function() {
    $('#searchBtn').click();
  });

  $( "#select_sector" ).select2({
    theme: "bootstrap"
  });

  $( "#select_leader" ).select2({
    theme: "bootstrap"
  });

  $( "#select_gender" ).select2({
    theme: "bootstrap"
  });

  $( "#select_on_behalf" ).select2({
    theme: "bootstrap"
  });

  $( "#select_esi" ).select2({
    theme: "bootstrap"
  });

  $( "#select_tpri" ).select2({
    theme: "bootstrap"
  });


  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-90556377-1', 'auto');
  ga('send', 'pageview');


</script>

app/views/members/indexfilterrific.html.erb
<% provide(:title, "Members Index") %>
<p id="notice"><%= notice %></p>

  <h1>Members</h1>
  <%= link_to 'New Member', new_member_path %><br>

  <%= form_for_filterrific @filterrific do |f| %>
  <div>
    Search
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    <%= f.text_field(
      :search_query,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>
  <div>
    Sector
    <%= f.select(
      :with_sector_id,
      @filterrific.select_options[:with_sector_id],
      { include_blank: '- Any -' }
    ) %>
  </div>
  <div>
    Sorted by
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
  </div>
  <div>
    <%= link_to(
      'Reset filters',
      reset_filterrific_url,
    ) %>
  </div>
  <%# add an automated spinner to your form when the list is refreshed %>
  <%= render_filterrific_spinner %>
  <% end %>

  <%= render(
  partial: 'members/list',
  locals: { members: @members }
  ) %>

<% if @members.blank? %>
  <h4>There are no names containing the term <%= params[:search] %>.</h4>
<% end %>


<!-- <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.js"></script> -->


&nbsp;

app/views/members/indexoriginal.html.erb
<% provide(:title, "Members Index") %>
<p id="notice"><%= notice %></p>

  <%= form_tag(members_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Database" %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>

<% if @members.blank? %>
  <h4>There are no names containing the term <%= params[:search] %>.</h4>
<% end %>

<h1>Members</h1>
<%= link_to 'New Member', new_member_path %><br>
<!-- <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.js"></script> -->

<div id="no-more-tables">
  <table id="table_id" class="col-md-12 table-bordered table-condensed cf display">
  <thead class="cf">
    <tr>
      <th>ID</th>
      <th>IC Name</th>
      <th>Common Name</th>
      <th>IC Number</th>
      <th>Handphone Number</th>
      <th>Gender</th>
      <th>Sector</th>
      <th>Leadership?</th>
      <th>Leader's Name</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr style="<%= 'background-color:#EBF5FB;' if member.gender == true %><%= 'background-color:#FDEDEC;' if member.gender == false %>">
        <td><%= member.id %></td>
        <td><%= member.ic_name %></td>
        <td><%= member.common_name %></td>
        <td><%= member.ic_no %></td>
        <td><%= member.handphone%></td>
        <td><%= member.gender ? "Male" : "Female" %></td>
        <td><%= member.sector ? member.sector.sector_type : '' %></td>
        <td><%= member.is_leader ? "Yes" : "No" %></td>
        <td><%= member.leader ? member.leader.common_name : '' %></td>
        <td><%= link_to 'Show', member %>&nbsp;&nbsp;&nbsp;
            <%= link_to 'Edit', edit_member_path(member) %>&nbsp;&nbsp;&nbsp;
            <%= link_to 'Delete', member, class: 'delete', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
&nbsp;

app/views/members/member_group.html.erb
<h1>Member group</h1>
<% @members = @members.select { |x| x.sector.active } %>
<% if @member.member_group_leader %>
    <table>
      <tbody>
        <% @member.member_group_leader.member_groups.each do |member| %>
          <tr>
          <td><%= member.common_name %></td>
          <td><%= link_to "Delete", member_delete_member_group_path(member) unless member == @member.member_group_leader %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="row" style="margin-top:30px">
    <%= select_tag "member", options_from_collection_for_select(@members, "id", "common_name", include_blank: true), id: "mselect" %>
    </div>
    <div class="row" style="margin-top:20px">
    <a id="btn-submit" class="btn btn-primary">Add</a>
    </div>

<% else %>
  No member group<br />
  <%= link_to "Create group", member_create_member_group_path(@member), class: "btn btn-primary" %>
<% end %>

<script>
$( "#mselect" ).select2({
  theme: "bootstrap"
});
$('#btn-submit').on('click', function() {
  var result = $("#mselect").val()
  var url = '<%= member_add_member_group_path(@member) %>?new_member_id=' + result;
  //console.log(result);
  window.location.href = url;
})
</script>